- repo: https://gitlab.com/pycqa/flake8
  rev: ''  # pick a git hash / tag to point to
  hooks:
    - id: flake8
      additional_dependencies: [flake8-docstrings]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
